### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by WhoIsDoctorWho** [WhoIsDoctorWho/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by timchnk** [comment]
Якщо там є фото з нашого чемпіонату в літрбол, вставляти не варто

**Comment by WhoIsDoctorWho** [comment]
Дякую за пораду, контент було обрано!
